# Generated by Django 5.2.11 on 2026-02-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placemodel",
            name="land_use_description",
            field=models.TextField(default="no_description"),
        ),
    ]
