# Generated by Django 5.2.11 on 2026-02-19 00:52

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_placemodel_land_use_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandUseGeometryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("land_use_geometry", models.TextField(db_index=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
            ],
            options={
                "db_table": "land_use_geometry",
            },
        ),
        migrations.RemoveField(
            model_name="placemodel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="placemodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="placemodel",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="placemodel",
            name="land_use_description",
            field=models.TextField(),
        ),
    ]
