from http import HTTPStatus
from .base import AppErrorCode


class AuthErrorCode(AppErrorCode):

    INVALID_CREDENTIALS = ("AUTH_INVALID_CREDENTIALS", HTTPStatus.UNAUTHORIZED)
    USER_NOT_FOUND = ("AUTH_USER_NOT_FOUND", HTTPStatus.NOT_FOUND)
    USER_INACTIVE = ("AUTH_USER_INACTIVE", HTTPStatus.FORBIDDEN)

    EMAIL_ALREADY_EXISTS = ("AUTH_EMAIL_ALREADY_EXISTS", HTTPStatus.CONFLICT)
    USERNAME_ALREADY_EXISTS = ("AUTH_USERNAME_ALREADY_EXISTS", HTTPStatus.CONFLICT)

    INVALID_TOKEN = ("AUTH_INVALID_TOKEN", HTTPStatus.UNAUTHORIZED)
    EXPIRED_TOKEN = ("AUTH_EXPIRED_TOKEN", HTTPStatus.UNAUTHORIZED)
    TOKEN_NOT_PROVIDED = ("AUTH_TOKEN_NOT_PROVIDED", HTTPStatus.UNAUTHORIZED)

    PERMISSION_DENIED = ("AUTH_PERMISSION_DENIED", HTTPStatus.FORBIDDEN)

    AUTH_ERROR = ("AUTH_ERROR", HTTPStatus.BAD_REQUEST)
