from http import HTTPStatus
from .base import AppErrorCode


class ProductErrorCode(AppErrorCode):
    NOT_FOUND = ("PRODUCT_NOT_FOUND", HTTPStatus.NOT_FOUND)
    ALREADY_EXISTS = ("PRODUCT_ALREADY_EXISTS", HTTPStatus.CONFLICT)

    INVALID_PRICE = ("PRODUCT_INVALID_PRICE", HTTPStatus.BAD_REQUEST)
    INVALID_QUANTITY = ("PRODUCT_INVALID_QUANTITY", HTTPStatus.BAD_REQUEST)
    INSUFFICIENT_STOCK = ("PRODUCT_INSUFFICIENT_STOCK", HTTPStatus.CONFLICT)

    STOCK_OPERATION_INVALID = (
        "PRODUCT_STOCK_OPERATION_INVALID",
        HTTPStatus.BAD_REQUEST,
    )

    PRODUCT_ERROR = ("PRODUCT_ERROR", HTTPStatus.BAD_REQUEST)
